Repository Os-Derivados/college-management, pull requests merged in 2024-12, with the labels that each got.

#20 Fix/14 ordem relatorio
  college-management/Contextos/ContextoUsuarios.cs
  college-management/Dados/Modelos/Aluno.cs
  college-management/Dados/Modelos/Funcionario.cs
  college-management/Dados/Modelos/Usuario.cs
  college-management/Utilitarios/UtilitarioCriptografia.cs
  college-management/Utilitarios/UtilitarioSeed.cs
Labels: bug

#26 Update README.md
  README.md
Labels: documentation

#32 Alterado o comando para criar o arquivo .env no windows
  README.md
Labels: documentation

#36 fix: (#35) utilizando valor correto na criação do hash
  college-management/Dados/CredenciaisUsuario.cs
Labels: bug

#38 Desenvolvido os métodos para Cadastrar, Visualizar, Ver Detalhes, Editar e Excluir Materias (Código refatorado)
  college-management/Contextos/ContextoMaterias.cs
Labels: enhancement

#28 fix: (#27) propriedades vazias tratadas corretamente
  college-management/Utilitarios/UtilitarioTipos.cs
Labels: bug

#33 fix: Inclui aviso em vez de exceção ao analisar argumentos de linha de comando
  college-management/Program.cs
  college-management/Utilitarios/UtilitarioSeed.cs
Labels: enhancement

#49 Verifica se o usuário foi criado com sucesso antes de prosseguir
  college-management/Utilitarios/UtilitarioSeed.cs
Labels: bug

#48 Usar varíaveis de ambiente nos comandos de criação do .env
  README.md
Labels: documentation
